- name: printing variables 
  hosts: local 
  connection: local 
  vars: 
    COURSE: "Ansible course" 
    DURATION: "10Hr" 
    TRAINER: "Sivakumar mettukuru"
  tasks: 
  - name: print course information
    ansible.builtin.debug: 
      msg: "Hello course is {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 
