- name: variables from files 
  hosts: local 
  connection: local 
  vars_files: 
  - course.yaml 
  tasks: 
  - name: print course information from files 
    ansible.builtin.debug: 
      msg: "hello course is {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 
      
