- name: using when condition
  hosts: local 
  connection: local 
  vars: 
    NUMBER: 100
  tasks: 
  - name: print a number if it is lessthan or equal to 100 
    ansible.builtin.debug: 
      msg: "given number {{ NUMBER }} is lessthan or equal to 100" 
    when: NUMBER <= 100 

  - name: print if a number is graterthan 100 
    ansible.builtin.debug: 
      msg: "given number {{ NUMBER }} is graterthan 100" 
    when: NUMBER > 100      