- name: writing playbook using ansible facts 
  hosts: frontend 
  become: yes 
  tasks: 
  - name: installing nginx if RedHat 
    ansible.builtin.dnf: 
      name: nginx 
      state: present 
    when: ansible_os_family == "RedHat"   

  - name: installing nginx if Debian 
    ansible.builtin.apt: 
      name: nginx 
      state: present 
    when: ansible_os_family == "Debian"      