- name: loops demo 
  hosts: local  
  connection: local 
  tasks: 
  - name: printing names 
    ansible.builtin.debug: 
      msg: "{{ item }}"
    loop:
    - suresh
    - dinesh
    - deepthi 
    - venkatesh   