- name: functions demo 
  hosts: local 
  connection: local 
  vars: 
    fruits: apple,banana,orange,mango 
    persons: ramesh,suresh,dinesh,deepthi 
  tasks: 
  - name: checking undefined variable 
    ansible.builtin.debug: 
      msg: "Hello, {{ person | default('dinesh') }}" 

  - name: transforming string into list 
    ansible.builtin.debug: 
      msg: "fruits are {{ fruits | split(',') }}" 

  - name: transforming string into list 
    ansible.builtin.debug: 
      msg: "persons are {{ persons | split(',') }}"   

  - name: convert map into list 
    vars: 
      course: 
        name: ansible 
        duration: 10Hrs
        trainer: sivakumar 
    ansible.builtin.debug: 
      msg: "course info {{ course | dict2items }}"  

  - name: convert list into map 
    vars: 
      course: 
      - {'key': 'name', 'value': 'ansible'} 
      - {'key': 'duration', 'value': '10Hrs'} 
      - {'key': 'trainer', 'value': 'sivakumar'} 
    ansible.builtin.debug: 
      msg: "course info {{ course | items2dict }}" 

  - name: convert into upper case 
    vars: 
      name: deepthi durgam 
    ansible.builtin.debug: 
      msg: "{{ name | upper }}" 

  - name: convert into lower case 
    vars: 
      name: DURGAM DEEPTHI 
    ansible.builtin.debug: 
      msg: "{{ name | lower }}"                           
